/*$file${../main::mqtt_settings.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: wifi.qm
* File:  ${../main::mqtt_settings.h}
*
* This code has been generated by QM 5.2.4 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../main::mqtt_settings.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef MQTT_SETTINGS_H
#define MQTT_SETTINGS_H

#define     IN_TOPIC        "devices/in/bip-esp-32/112233445566"
#define     OUT_TOPIC       "devices/out/bip-esp-32/112233445566"
#define     MQTT_URI        "mqtt://emqx.bip.app-server.net/"
#define     MQTT_PORT        (1883)

#define     MQTT_USERNAME       "iot_device"
#define     MQTT_PASSWORD       "qwerty"

#endif //MQTT_SETTINGS_H
