/*$file${../main::qhsm-button.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: wifi.qm
* File:  ${../main::qhsm-button.c}
*
* This code has been generated by QM 5.2.4 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../main::qhsm-button.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"

#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"

#include "bsp.h"
#include "wifi_button.h"

static const char * TAG = "button";

/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 700U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.0.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Button} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Button} ...........................................................*/
Button Button_obj;

/*${AOs::Button::SM} .......................................................*/
QState Button_initial(Button * const me, void const * const par) {
    /*${AOs::Button::SM::initial} */
    ESP_LOGI(TAG, "Button Initial transition");
    QActive_subscribe(&me->super, BUTTON_PRESSED_SIG);
    return Q_TRAN(&Button_Button);
}

/*${AOs::Button::SM::Button} ...............................................*/
QState Button_Button(Button * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Button::SM::Button::BUTTON_PRESSED} */
        case BUTTON_PRESSED_SIG: {
            switch (Q_EVT_CAST(ButtonEvt)->buttonNum) {
                case BUTTON_A: {
                    ButtonEvt *pe = Q_NEW(ButtonEvt, CONNECT_SIG);
                    QACTIVE_PUBLISH(&pe->super, AO_Button);
                    break;
                }

                case BUTTON_B: {
                    ButtonEvt *pe = Q_NEW(ButtonEvt, DISCONNECT_SIG);
                    QACTIVE_PUBLISH(&pe->super, AO_Button);
                    break;
                }

                case BUTTON_C: {
                    me->press_cntr++;
                    if (me->press_cntr % 2)
                    {
                        ButtonEvt *pe = Q_NEW(ButtonEvt, STOP_TELEMETRY_SIG);
                        QACTIVE_PUBLISH(&pe->super, AO_Button);
                    }
                    else
                    {
                        ButtonEvt *pe = Q_NEW(ButtonEvt, START_TELEMETRY_SIG);
                        QACTIVE_PUBLISH(&pe->super, AO_Button);
                    }
                    break;
                }

                default:
                break;
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Button} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${Shared::Button_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${Shared::Button_ctor} ...................................................*/
void Button_ctor(void) {
    Button *me = &Button_obj;

    QActive_ctor(&Button_obj.super, Q_STATE_CAST(&Button_initial));
    me->press_cntr = 0;
}
/*$enddef${Shared::Button_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${Shared::AO_Button} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${Shared::AO_Button} .....................................................*/
QActive * const AO_Button  = &Button_obj.super;
/*$enddef${Shared::AO_Button} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
