/*$file${../main::sensor.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: wifi.qm
* File:  ${../main::sensor.c}
*
* This code has been generated by QM 5.2.4 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../main::sensor.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"
#include "esp_log.h"
#include "bsp.h"
#include "wifi_button.h"

static const char *TAG = "Sensor";

/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 700U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.0.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Sensor} ...........................................................*/
Sensor Sensor_obj;

/*${AOs::Sensor::SM} .......................................................*/
QState Sensor_initial(Sensor * const me, void const * const par) {
    /*${AOs::Sensor::SM::initial} */
    // Subscribt to required signals from QF
    QActive_subscribe(&me->super, START_TELEMETRY_SIG);
    QActive_subscribe(&me->super, STOP_TELEMETRY_SIG);
    return Q_TRAN(&Sensor_active);
}

/*${AOs::Sensor::SM::active} ...............................................*/
QState Sensor_active(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Sensor::SM::active::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Sensor_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Sensor::SM::active::idle} .........................................*/
QState Sensor_idle(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Sensor::SM::active::idle} */
        case Q_ENTRY_SIG: {
            ESP_LOGI(TAG, "Sensor IDLE state");
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sensor::SM::active::idle::START_TELEMETRY} */
        case START_TELEMETRY_SIG: {
            status_ = Q_TRAN(&Sensor_read_data);
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_active);
            break;
        }
    }
    return status_;
}

/*${AOs::Sensor::SM::active::read_data} ....................................*/
QState Sensor_read_data(Sensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Sensor::SM::active::read_data} */
        case Q_ENTRY_SIG: {
            printf("Sensor READ DATA state");

            QTimeEvt_armX(&me->measTimeEvt, BSP_TICKS_PER_SEC/2U,
                          BSP_TICKS_PER_SEC/2U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sensor::SM::active::read_data} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->measTimeEvt);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sensor::SM::active::read_data::STOP_TELEMETRY} */
        case STOP_TELEMETRY_SIG: {
            status_ = Q_TRAN(&Sensor_idle);
            break;
        }
        /*${AOs::Sensor::SM::active::read_data::MEAS_TIMEOUT} */
        case MEAS_TIMEOUT_SIG: {
            float t, p;

            read_bmp280_data(&t, &p);
            me->sensor_data.temperature = t;
            me->sensor_data.pressure = p;

            SensorEvt *pe = Q_NEW(SensorEvt, SEND_MEAS_SIG);
            pe->temperature = t;
            pe->pressure = p;
            QACTIVE_PUBLISH(&pe->super, AO_Sensor);

            //printf("Temp: %.2f Pressure: %.2f \n", t, p);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Sensor_active);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${Shared::SensorEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*$enddef${Shared::SensorEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${Shared::AO_Sensor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${Shared::AO_Sensor} .....................................................*/
QActive * const AO_Sensor  = &Sensor_obj.super;
/*$enddef${Shared::AO_Sensor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${Shared::Sensor_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${Shared::Sensor_ctor} ...................................................*/
void Sensor_ctor(void) {
    Sensor *me = &Sensor_obj;

    QActive_ctor(&Sensor_obj.super, Q_STATE_CAST(&Sensor_initial));
    QTimeEvt_ctorX(&me->measTimeEvt, &me->super, MEAS_TIMEOUT_SIG, 0U);
}
/*$enddef${Shared::Sensor_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
