/*$file${../main::wifi_button.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: wifi.qm
* File:  ${../main::wifi_button.h}
*
* This code has been generated by QM 5.2.4 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${../main::wifi_button.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef WF_BUTTON_H
#define WF_BUTTON_H

#define DEBOUNCE_TIME 3

enum wifiSignals {
    DISCONNECTED_SIG = Q_USER_SIG,
    STA_STARTED_SIG,
    CONNECT_SIG,
    CONNECTED_SIG,
    CONNECTION_LOST_SIG,
    GOT_IP_SIG,
    LOST_IP_SIG,
    BUTTON_PRESSED_SIG,
    DISCONNECT_BUTTON_B_SIG,
    MAX_PUB_SIG
};

/*$declare${Events::ButtonEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${Events::ButtonEvt} .....................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    uint8_t buttonNum;
} ButtonEvt;
/*$enddecl${Events::ButtonEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${AOs::Peripherals::Button} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Peripherals::Button} ..............................................*/
typedef struct Button {
/* protected: */
    QActive super;

/* public: */

/* private: */
    QTimeEvt timeEvt;
} Button;
extern Button Button_obj;

/* protected: */
QState Button_initial(Button * const me, void const * const par);
QState Button_Button(Button * const me, QEvt const * const e);
/*$enddecl${AOs::Peripherals::Button} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${AOs::Ctors::Button_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Ctors::Button_ctor} ...............................................*/
void Button_ctor(void);
/*$enddecl${AOs::Ctors::Button_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${AOs::Opaque_pointers::AO_Button} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Opaque_pointers::AO_Button} .......................................*/
extern QActive * const AO_Button;
/*$enddecl${AOs::Opaque_pointers::AO_Button} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$declare${Events::WifiEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${Events::WifiEvt} .......................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    uint8_t n;
} WifiEvt;
/*$enddecl${Events::WifiEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${AOs::Connectivity::WiFi} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Connectivity::WiFi} ...............................................*/
typedef struct WiFi {
/* protected: */
    QActive super;

/* public: */
} WiFi;
extern WiFi WiFi_obj;

/* protected: */
QState WiFi_initial(WiFi * const me, void const * const par);
QState WiFi_sta_started(WiFi * const me, QEvt const * const e);
QState WiFi_connected(WiFi * const me, QEvt const * const e);
QState WiFi_disconnect(WiFi * const me, QEvt const * const e);
QState WiFi_try_connect(WiFi * const me, QEvt const * const e);
QState WiFi_got_ip(WiFi * const me, QEvt const * const e);
QState WiFi_buttons_dispatch(WiFi * const me, QEvt const * const e);
QState WiFi_init(WiFi * const me, QEvt const * const e);
/*$enddecl${AOs::Connectivity::WiFi} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${AOs::Ctors::WiFi_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Ctors::WiFi_ctor} .................................................*/
void WiFi_ctor(void);
/*$enddecl${AOs::Ctors::WiFi_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$declare${AOs::Opaque_pointers::AO_WiFi} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Opaque_pointers::AO_WiFi} .........................................*/
extern QActive * const AO_WiFi;
/*$enddecl${AOs::Opaque_pointers::AO_WiFi} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif
